### ISSUE TITLE
Goop cant clone private repository

### ISSUE THREAD

**Issue by dqminh** [petejkim/goop#10]
By default, Goop use `go get -u [REPO]`, however `go get -u` cant fetch private dependencies.

The workaround right now is to use `.netrc` file to specify credentials for the remote repository (i.e. github), but it would be nice to be able to specify a git src and use it.

**Comment by keyist** [comment]
More convenient workaround would be adding to git config:

```
[url "git@github:"]
  insteadOf = "https://github.com"
```

**Comment by petejkim** [comment]
I am adding the support for the following in the next version:

```
github.com/mattn/go-sqlite3
github.com/gorilla/context #14f550f51af52180c2eefed15e5fd18d63c0a64a
github.com/dotcloud/docker/pkg/proxy #v1.0.1 // comment
github.com/gorilla/mux !git@github.com:nitrous-io/mux.git // override repo url
```

**Comment by petejkim** [comment]
Implemented. See branch "repo-url-override" - https://github.com/nitrous-io/goop/tree/repo-url-override

**Comment by johntdyer** [comment]
Any reason this wasnt merged ?

**Comment by wjessop** [comment]
I ran into this issue today, would love to see it, or some other implementation merged!

**Comment by wjessop** [comment]
Ignore me, just saw in the README that is't possible now, thanks!

**Comment by arunthampi** [comment]
closed by https://github.com/nitrous-io/goop/commit/68edc60e171adf79ffdf5974958d275244c40d89
