### ISSUE TITLE
Allow comments

### ISSUE THREAD

**Issue by fisadev** [petejkim/goop#2]
Python developer here. You wouldn't believe how useful it is to allow comments on dependencies declarations, we do that all the time in the python world (in our requirements.txt files, used to install dependencies with the pip python tool).
Things like "don't update to newer versions, this is the last compatible one", or "we are using this for feature/module x", etc.

**Comment by petejkim** [comment]
good idea... probably something like

```
github.com/lib/pq #b549d8792f245c2dcee7702ddcd844280b8ecb10 // don't upgrade
```

**Comment by petejkim** [comment]
This is implemented in branch: https://github.com/nitrous-io/goop/tree/repo-url-override

We'll release the feature after more testing.

**Comment by fisadev** [comment]
Great! :)
