### ISSUE TITLE
Nested dependencies

### ISSUE THREAD

**Issue by eknkc** [petejkim/goop#6]
I might be mistaken, but it seems that goop creates a lock file for the top level dependencies only. For example, if I list module 'A' as a dependency and it has module 'B' as a dependency, my lock file will contain a revision hash for module A but nothing about module B.

Is that correct? If so, how can we make sure that changes to module B would not affect our locked versions in future?

**Comment by petejkim** [comment]
Thanks! This is being worked on.

**Comment by petejkim** [comment]
https://github.com/nitrous-io/goop/tree/lock-subdeps adds this, can you try it?

**Comment by petejkim** [comment]
merged to master
